version: '3.9'

services:
  frontend:
    build: ./frontend/
    restart: always
    container_name: frontend
    volumes:
      - './frontend:/app'
    ports:
      - '3000:3000'
    environment:
      BACK_API: backend:4000
    networks:
      - app

  backend:
    build: ./server/
    restart: always
    container_name: backend
    volumes:
      - './server:/app'
      - './server/node_modules/:/app/node_modules/'
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_PASSWORD: root
      DB_USER: root
      SECRET: 'any secret'
    depends_on:
      - mysql
    networks:
      - app

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app
  
  phpMyAdmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - app
volumes:
  mysql_data:

networks:
  app:
    driver: bridge