version: '3.9'

services:
  backend:
    build: ./server/
    restart: always
    container_name: backend
    volumes:
      - './server:/app'
      - './server/node_modules/:/app/node_modules/'
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_PASSWORD: root
      DB_USER: root
      SECRET: 'any secret'
    depends_on:
      - mysql
    networks:
      - app

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app
volumes:
  mysql_data:

networks:
  app:
    driver: bridge