import { Button } from '@chakra-ui/react'
import Head from 'next/head'
import { api } from '../api'
import { Link } from '../components/Link'
import { useUser } from '../hooks/useUser'

export default function Home() {
  const { user, isLoading, isError, mutate } = useUser({ redirect: false })

  if (isLoading) {
    return (
      <h1>Loading</h1>
    )
  }

  const logout = async () => {
    await api.logout()
    location.reload()
  }
  
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <div>
          {user ?
            <>
              <Link href='/chats'>Chats</Link>
              <Button onClick={logout}>Logout</Button>
            </>
          :
            <>
              <Link href='/signup'>Sign Up</Link> <br />
              <Link href='/signin'>Sign In</Link>
            </>
          }
        </div>
      </main>
    </div>
  )
}
